# connect travis and docker
sudo: required
services:
  - docker

# build image
before_install:
  - docker build -t faustaleonardo/docker-react -f Dockerfile.dev .

# create and run our container + test our web app
script:
  - docker run -e CI=true faustaleonardo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-327765756257"
  bucket_path: "docker-react"
  # specify that only code push to master will be deployed
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
